# Generated by Django 4.1.7 on 2023-03-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
